AssStyleOptionsList: Fix build regression by changing access type of GetDefaultFilePath() to public
Prevents error CS0117: 'AssStyleOptionsList' does not contain a definition for 'GetDefaultFilePath' in YTSubConverter.UI.Linux/MainWindow.cs(524,51).